FROM continuumio/miniconda3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY environment.yml ./
RUN conda env create --force -q -n cats -f environment.yml && echo "source activate cats" > ~/.bashrc
ENV PATH /opt/conda/envs/cats/bin:$PATH

WORKDIR /opt/apps/cattrack
COPY ./ ./

EXPOSE 8000
CMD gunicorn --env DJANGO_SETTINGS_MODULE=cattrack.settings_prod --workers 3 -b 0.0.0.0:8000 cattrack.wsgi:application