name: cats
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - beautifulsoup4=4.8.0
  - decorator=4.4.0
  - django=2.2.10
  - gunicorn=19.9.0
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - libpq=11.2
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.1
  - markdown=3.1.1
  - mkl=2019.4
  - numpy=1.17.2
  - openssl=1.1.1d
  - pandas=0.25.1
  - pastedeploy=2.0.1
  - path.py=12.0.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prompt_toolkit=2.0.9
  - psycopg2=2.8.3
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - readline=7.0
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - simplegeneric=0.8.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - coreapi==2.3.3
    - coreschema==0.0.4
    - django-cors-headers==3.1.0
    - django-crispy-forms==1.7.2
    - django-filter==2.2.0
    - djangorestframework==3.10.3
    - djangorestframework-jwt==1.11.0
    - ipdb==0.12.2
    - itypes==1.1.0
    - jinja2==2.10.1
    - markupsafe==1.1.1
    - ofxparse==0.20
    - pyjwt==1.7.1
    - uritemplate==3.0.0
