name: cattrack
dependencies:
- beautifulsoup4=4.5.1
- decorator=4.0.10
- django=1.9.5
- ipython=5.1.0
- ipython_genutils=0.1.0
- libxml2=2.9.2
- libxslt=1.1.28
- lxml=3.6.4
- mkl=11.3.3
- numpy=1.11.1
- openssl=1.0.2h
- pandas=0.18.1
- path.py=8.2.1
- pexpect=4.0.1
- pickleshare=0.7.3
- pip=8.1.2
- prompt_toolkit=1.0.3
- ptyprocess=0.5.1
- pygments=2.1.3
- python=3.5.2
- python-dateutil=2.5.3
- pytz=2016.6.1
- readline=6.2
- scikit-learn=0.17.1
- scipy=0.18.0
- setuptools=26.1.1
- simplegeneric=0.8.1
- six=1.10.0
- sqlite=3.13.0
- tk=8.5.18
- traitlets=4.2.2
- wcwidth=0.1.7
- wheel=0.29.0
- xz=5.2.2
- zlib=1.2.8
- pip:
  - ofxparse==0.15
