name: cats
channels:
- defaults
dependencies:
- appnope=0.1.0
- beautifulsoup4=4.5.1
- decorator=4.0.10
- django=1.11.3
- gunicorn=19.1.0
- ipython=5.1.0
- ipython_genutils=0.1.0
- libpq=9.5.4
- libxml2=2.9.2
- libxslt=1.1.28
- lxml=3.6.4
- markdown=2.6.6
- mkl=11.3.3
- numpy=1.11.1
- openssl=1.0.2h
- pandas=0.18.1
- pastedeploy=1.5.2
- path.py=8.2.1
- pexpect=4.0.1
- pickleshare=0.7.3
- pip=8.1.2
- prompt_toolkit=1.0.3
- psycopg2=2.6.2
- ptyprocess=0.5.1
- pygments=2.1.3
- python=3.5.2
- python-dateutil=2.5.3
- pytz=2016.6.1
- pyyaml=3.12
- readline=6.2
- requests=2.11.1
- scikit-learn=0.17.1
- scipy=0.18.0
- setuptools=26.1.1
- simplegeneric=0.8.1
- six=1.10.0
- sqlite=3.13.0
- tk=8.5.18
- traitlets=4.2.2
- wcwidth=0.1.7
- wheel=0.29.0
- xz=5.2.2
- yaml=0.1.6
- zlib=1.2.8
- pip:
  - coreapi==2.0.7
  - django-cors-headers==1.1.0
  - django-crispy-forms==1.6.0
  - django-filter==1.0.4
  - djangorestframework==3.4.6
  - djangorestframework-jwt==1.8.0
  - ipdb==0.10.1
  - ipython-genutils==0.1.0
  - itypes==1.1.0
  - ofxparse==0.15
  - prompt-toolkit==1.0.3
  - pyjwt==1.4.2
  - uritemplate==3.0.0
