# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('anchor_date', models.DateField(null=True)),
                ('frequency', models.CharField(max_length=10)),
            ],
        ),
    ]
