# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0002_perioddefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('var_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('document', models.FileField(null=True, upload_to='')),
                ('paying_transactions', models.ManyToManyField(related_name='pays_bill', to='ctrack.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_income', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='perioddefinition',
            name='anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='ctrack.RecurringPayment'),
        ),
    ]
