# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0003_auto_20160927_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_points', to='ctrack.Account')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-due_date']},
        ),
    ]
