# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0005_auto_20171004_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPdfScraperConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('label_pattern', models.CharField(max_length=50)),
                ('value_pattern', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=200)),
            ],
        ),
    ]
