# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0006_billpdfscraperconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='document',
            field=models.FileField(null=True, upload_to='uploaded/bills'),
        ),
    ]
