# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 09:53
from __future__ import unicode_literals

from django.db import models, migrations


def make_many_authors(apps, schema_editor):
    """
        Adds the Category object in BudgetEntry.category to the
        many-to-many relationship in BudgetEntry.categories
    """
    BudgetEntry = apps.get_model('ctrack', 'BudgetEntry')

    for entry in BudgetEntry.objects.all():
        entry.categories.add(entry.category)


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0009_auto_20180107_0950'),
    ]

    operations = [
        migrations.RunPython(make_many_authors),
    ]