# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0010_auto_20180107_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='category',
        ),
    ]
