# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0011_remove_budgetentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
