# Generated by Django 2.2.28 on 2022-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0012_budgetentry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorisorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('implementation', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('model', models.BinaryField()),
            ],
        ),
    ]
