# Generated by Django 2.2.28 on 2022-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0014_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='enable_db_categorisors',
            field=models.BooleanField(default=False),
        ),
    ]
