# Generated by Django 5.2.9 on 2026-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0016_alter_account_id_alter_balancepoint_id_alter_bill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(related_name='category_groups', to='ctrack.category')),
            ],
            options={
                'verbose_name_plural': 'category groups',
                'ordering': ['name'],
            },
        ),
    ]
