# Generated by Django 5.2.9 on 2026-05-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrack', '0019_categorisormodel_training_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorisormodel',
            options={'verbose_name': 'categorisor model', 'verbose_name_plural': 'categorisor models'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'user settings', 'verbose_name_plural': 'user settings'},
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ctrack.account'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['due_date'], name='ctrack_bill_due_dat_9c1d14_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['when'], name='ctrack_tran_when_2447c7_idx'),
        ),
    ]
